# Generated by Django 5.1.4 on 2025-01-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=16, null=True)),
                ('username', models.CharField(blank=True, max_length=64, null=True)),
                ('balance', models.IntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=8, verbose_name='Language')),
            ],
            options={
                'verbose_name': 'User Data',
                'verbose_name_plural': 'Users Data',
            },
        ),
    ]
