# Generated by Django 5.1.4 on 2025-12-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_in_row",
                    models.PositiveIntegerField(
                        help_text="Number of category buttons per row.",
                        verbose_name="Categories in Row",
                    ),
                ),
                (
                    "product_in_row",
                    models.PositiveIntegerField(
                        help_text="Number of product buttons per row.",
                        verbose_name="Products in Row",
                    ),
                ),
                (
                    "number_of_transactions",
                    models.PositiveIntegerField(
                        help_text="Transactions shown per page in history.",
                        verbose_name="Num of Transaction",
                    ),
                ),
                (
                    "number_of_product",
                    models.PositiveIntegerField(
                        help_text="Purchase history displayed per page.",
                        verbose_name="Num of Products in Purchase",
                    ),
                ),
                (
                    "wallet_currency",
                    models.CharField(
                        help_text="Ex: USD, RUB, CAD, ...",
                        max_length=8,
                        verbose_name="Wallet Currency",
                    ),
                ),
                (
                    "wallet_currency_sign",
                    models.CharField(
                        help_text="Ex: $, ₽, ...",
                        max_length=8,
                        verbose_name="Wallet Currency Sign",
                    ),
                ),
                (
                    "ton_price_delay",
                    models.PositiveIntegerField(
                        help_text="Interval between price updates in seconds.",
                        verbose_name="TON Price Delay (seconds)",
                    ),
                ),
                (
                    "ton_fetch_limit",
                    models.PositiveIntegerField(
                        help_text="Number of transactions fetched per request.\nlimit should be less or equal 1000",
                        verbose_name="TON Fetch Limit",
                    ),
                ),
                (
                    "ton_network_delay",
                    models.PositiveIntegerField(
                        help_text="Interval between deposit address checks(Fetch transactions)",
                        verbose_name="TON Network Delay (seconds)",
                    ),
                ),
                (
                    "ton_deposit_address",
                    models.CharField(
                        max_length=256, verbose_name="TON Deposit Address"
                    ),
                ),
                (
                    "ton_deposit_domain",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="TON Deposit Domain",
                    ),
                ),
                (
                    "ton_network_api_key",
                    models.CharField(
                        help_text="Provided by @tonapibot",
                        max_length=256,
                        verbose_name="TON Network API Key",
                    ),
                ),
                (
                    "cmc_api_key",
                    models.CharField(
                        default="",
                        help_text="Get api key from https://coinmarketcap.com/api/pricing/",
                        max_length=256,
                        verbose_name="CoinMarketCap API Key",
                    ),
                ),
                (
                    "ton_api_io_key",
                    models.CharField(
                        default="",
                        help_text="Get api key from https://tonapi.io/",
                        max_length=256,
                        verbose_name="tonapi.io API Key",
                    ),
                ),
                (
                    "telegram_wallet_link",
                    models.CharField(
                        default="https://t.me/wallet/start?startapp=tonspace_main",
                        max_length=256,
                        verbose_name="@Wallet",
                    ),
                ),
                (
                    "disable_product_images",
                    models.BooleanField(
                        default=True,
                        help_text="Enable this to hide product images for a cleaner interface and faster loading.",
                        verbose_name="Disable Product Images",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Settings",
                "verbose_name_plural": "Bot Settings",
            },
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=64, null=True)),
                ("last_name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "balance",
                    models.DecimalField(
                        db_index=True, decimal_places=4, default=0.0, max_digits=18
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=8, verbose_name="Language"
                    ),
                ),
                ("utc_offset", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name": "User Data",
                "verbose_name_plural": "Users Data",
            },
        ),
    ]
