# Generated by Django 5.1.4 on 2025-01-10 23:09

import django.db.models.deletion
import encrypted_json_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Category Name')),
                ('name_fa', models.CharField(max_length=32, null=True, unique=True, verbose_name='Category Name')),
                ('name_en', models.CharField(max_length=32, null=True, unique=True, verbose_name='Category Name')),
                ('name_du', models.CharField(max_length=32, null=True, unique=True, verbose_name='Category Name')),
                ('is_delete', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Product Name')),
                ('name_fa', models.CharField(max_length=32, null=True, verbose_name='Product Name')),
                ('name_en', models.CharField(max_length=32, null=True, verbose_name='Product Name')),
                ('name_du', models.CharField(max_length=32, null=True, verbose_name='Product Name')),
                ('price', models.IntegerField(verbose_name='Product Price')),
                ('is_delete', models.BooleanField(blank=True, default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', encrypted_json_fields.fields.EncryptedCharField(crypter=None, verbose_name='Details')),
                ('is_purchased', models.BooleanField(default=False, verbose_name='Is Purchased')),
                ('purchase_date', models.DateTimeField(blank=True, null=True, verbose_name='Purchased  Date')),
                ('is_delete', models.BooleanField(blank=True, default=False)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userdata', verbose_name='Buyer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Detail',
                'verbose_name_plural': 'Products Detail',
                'ordering': ['-is_purchased'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'name_fa'), name='unique_name_fa_per_category'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'name_en'), name='unique_name_en_per_category'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'name_du'), name='unique_name_du_per_category'),
        ),
    ]
