# Generated by Django 5.1.4 on 2025-12-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TonCursor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=32, unique=True)),
                ("last_lt", models.BigIntegerField(default=0)),
                (
                    "last_hash",
                    models.CharField(blank=True, default="", max_length=128, null=True),
                ),
            ],
            options={
                "verbose_name": "Ton Cursor",
                "verbose_name_plural": "Ton Cursor",
            },
        ),
        migrations.CreateModel(
            name="TonPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_per_ton",
                    models.DecimalField(decimal_places=2, max_digits=18, null=True),
                ),
                (
                    "price_currency",
                    models.CharField(default="usd", max_length=8, null=True),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ton Price",
                "verbose_name_plural": "Ton Price",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=9, max_digits=18, verbose_name="TON amount"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Memo/tag/Comment"
                    ),
                ),
                ("tx_id", models.CharField(max_length=128, unique=True)),
                (
                    "lt",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Logical Time"
                    ),
                ),
                (
                    "price_per_ton",
                    models.DecimalField(decimal_places=4, max_digits=18, null=True),
                ),
                (
                    "price_currency",
                    models.CharField(default="usd", max_length=8, null=True),
                ),
                ("paid_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.userdata",
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-paid_time"],
            },
        ),
    ]
