# Generated by Django 5.1.4 on 2025-01-10 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('tracking_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('amount', models.IntegerField()),
                ('paid_time', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdata', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-paid_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='amount_positive')],
            },
        ),
    ]
