# Generated by Django 5.1.4 on 2025-12-15 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TonPrice",
        ),
    ]
